# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20161230_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personal_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
