# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_person_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
