# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import mixins


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20170101_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=mixins.ImageUploaderMixin.set_path, verbose_name='Photo'),
        ),
    ]
