# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import mixins


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20170119_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to=mixins.ImageUploaderMixin.set_path, verbose_name='Photo'),
        ),
    ]
